import { css } from "@/styled-system/css";
import { Spoiler } from "@liquity2/uikit";

export function VaultFAQPanel() {
  return (
    <div
      className={css({
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: "100%",
        gap: 16,
        padding: "24px 0 24px 0",
        borderTop: "1px solid token(colors.fieldBorder)",
      })}
    >
      <div className={css({
        display: "flex",
        flexDirection: "column",
        gap: 16,
      })}>
        <h2
          className={css({
            fontSize: 28,
            marginBottom: 4,
          })}>
          FAQ
        </h2>
        <Spoiler title="What is sbvUSD?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            sbvUSD is the <span className={css({ fontWeight: 600, color: "white" })}>yield-bearing variant of bvUSD</span>, BitVault’s institutional-grade, over-collateralized, Bitcoin-backed stablecoin. When you stake your bvUSD into sbvUSD, you begin earning real yield generated by non-directional, institutional strategies managed by premier partners like <span className={css({ fontWeight: 600, color: "white" })}>GSR</span>.
          </p>
        </Spoiler>
        <Spoiler title="How does sbvUSD generate yield?" marginBottom={4}>
          <div
            className={css({
              color: "contentAlt",
            })}
          >
            <p >
              Yield in sbvUSD is generated through <span className={css({ fontWeight: 600, color: "white" })}>capital-efficient arbitrage strategies</span> like basis trading and cross-exchange arbitrage. These strategies are managed by whitelisted institutional curators, such as GSR and LM5, who deploy capital across permissioned vaults designed for <span className={css({ fontWeight: 600, color: "white" })}>low-risk, stable returns</span>.
            </p>
            <ul style={{ listStyleType: "disc", listStylePosition: "inside" }}>
              <li>
                Strategies are non-directional (market-neutral)
              </li>
              <li>
                Designed for sustainable, long-term yield (12% APY target)
              </li>
              <li>
                Deployed via battle-tested infrastructure (VaultCraft V2)
              </li>
            </ul>
          </div>
        </Spoiler>
        <Spoiler title="Is sbvUSD safe?" marginBottom={4}>
          <div
            className={css({
              color: "contentAlt",
            })}
          >
            <p >
              Yes, sbvUSD is built with <span className={css({ fontWeight: 600, color: "white" })}>security-first design principles:</span>
            </p>
            <ul style={{ listStyleType: "disc", listStylePosition: "inside" }}>
              <li>
                Backed 1:1 by bvUSD (which is itself over-collateralized by BTC) and stablecoins
              </li>
              <li>
                Strategies are managed by whitelisted, audited institutions
              </li>
              <li>
                Automated risk management using institutional curators
              </li>
              <li>
                Real-time monitoring via Hypernative
              </li>
              <li>
                Audits can be found <a href="https://docs.bitvault.finance/security/audits" target="_blank" rel="noopener noreferrer" className={css({ color: "gold" })}>here</a>
              </li>
            </ul>
          </div>
        </Spoiler>
        <Spoiler title="Who can mint sbvUSD?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            Anyone who holds <span className={css({ fontWeight: 600, color: "white" })}>bvUSD or stablecoins</span>, can stake it to mint sbvUSD and start earning yield. It’s a <span className={css({ fontWeight: 600, color: "white" })}>permissionless earn mechanism</span>, meaning you don’t need to be an institution to participate in yield generation. Simply stake and earn.
          </p>
        </Spoiler>
        <Spoiler title="What are the risks?" marginBottom={4}>
          <div
            className={css({
              color: "contentAlt",
            })}
          >
            <p >
              Like all DeFi products, sbvUSD is not risk-free. Potential risks include:
            </p>
            <ul style={{ listStyleType: "disc", listStylePosition: "inside" }}>
              <li>
                Smart contract vulnerabilities (mitigated via audits & live monitoring)
              </li>
              <li>
                Strategy underperformance (mitigated by institutional-grade partners)
              </li>
              <li>
                Collateral volatility (backed by BTC, but over-collateralized ≥150%)
              </li>
            </ul>
            <p >
              However, sbvUSD minimizes risk through:
            </p>
            <ul style={{ listStyleType: "disc", listStylePosition: "inside" }}>
              <li>
                Institutional-grade custody using ForDeFi
              </li>
              <li>
                Over-collateralization
              </li>
              <li>
                Permissioned curators
              </li>
            </ul>
          </div>
        </Spoiler>
        <Spoiler title="How and when can I unstake sbvUSD?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            You can request to unstake sbvUSD at any time. However, redemptions are processed on a monthly basis during a fixed 3-day window at the end of each month (starting at 9AM CET on the 28th). This batching mechanism allows underlying capital to be unwound efficiently while preserving yield for remaining participants. Requests submitted before the window will be queued for the next redemption cycle.
          </p>
        </Spoiler>
        <Spoiler title="What is the expected APY?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            sbvUSD targets a net <span className={css({ fontWeight: 600, color: "white" })}>APY of 12%</span>, though this may vary depending on market conditions. Yield is auto-compounded, and updates are transparently displayed on the BitVault dashboard.
          </p>
        </Spoiler>
        <Spoiler title="How is yield calculated and distributed?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            sbvUSD accrues value over time. As yield is generated from strategy profits, it is reflected as a <span className={css({ fontWeight: 600, color: "white" })}>gradual increase in sbvUSD's exchange rate back to bvUSD</span>. There are <span className={css({ fontWeight: 600, color: "white" })}>no fixed payouts</span> — your holdings grow in value directly within your wallet.
          </p>
        </Spoiler>
        <Spoiler title="Who manages the strategies behind sbvUSD?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            sbvUSD vaults are managed by <span className={css({ fontWeight: 600, color: "white" })}>whitelisted institutional partners</span>, including GSR, Re7 and LM5.
            All curators are selected based on performance, transparency, and alignment with BitVault’s security and compliance standards.
          </p>
        </Spoiler>
        <Spoiler title="Is sbvUSD available to everyone?" marginBottom={4}>
          <p className={css({
            color: "contentAlt",
          })}>
            sbvUSD is accessible anywhere except from Burma (Myanmar), Cuba, Iran, Sudan, Syria, the Western Balkans, Belarus, Côte d’Ivoire, Democratic Republic of the Congo, Iraq, Lebanon, Liberia, Libya, North Korea, Russia, certain sanctioned areas of Ukraine, Somalia, Venezuela, Yemen, Zimbabwe, or the United States of America (collectively, “Prohibited Jurisdictions”), or any other jurisdiction listed as a Specially Designated National by the United States Office of Foreign Asset Control (“OFAC”).
          </p>
        </Spoiler>
      </div>
    </div>
  )
}