name: Update Protocol Statistics

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  run-update-script:
    name: Run stats-script
    runs-on: ubuntu-latest

    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

    defaults:
      run:
        working-directory: frontend/stats-script

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Yarn 1.22
        run: npm install -g yarn@1.22.21

      - name: Install dependencies
        run: yarn install

      - name: Run update-stats script
        run: yarn run update-stats

      - name: Commit & push changes 
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update protocol stats file via cron"
          git push origin main
